### ISSUE TITLE
Edit a specification after execution gives the following error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#140]
**Expected behavior**
Should be able to work seamlessly

**Actual behavior**
<img width="960" alt="languageclientnotreadyyet" src="https://user-images.githubusercontent.com/6310197/36150073-58f097b4-10e8-11e8-8e6b-57e319f0e5a4.png">

```
panic: runtime error: index out of range

goroutine 182 [running]:
github.com/getgauge/gauge/parser.(*SpecParser).validateSpec(0xc04236ec00, 0xc042032800, 0x0, 0x0)
	src/github.com/getgauge/gauge/parser/specparser.go:579 +0x340
github.com/getgauge/gauge/parser.(*SpecParser).CreateSpecification(0xc04236ec00, 0xc04236c000, 0x24, 0x40, 0xc042038460, 0xc04236e840, 0x33, 0x40, 0x0, 0x0, ...)
	src/github.com/getgauge/gauge/parser/specparser.go:270 +0x100
github.com/getgauge/gauge/parser.(*SpecParser).Parse(0xc04236ec00, 0xc04207fc00, 0x331, 0xc042038460, 0xc04236e840, 0x33, 0x0, 0x0, 0x1, 0xc04236e2c0)
	src/github.com/getgauge/gauge/parser/specparser.go:72 +0xf2
github.com/getgauge/gauge/api/lang.validateSpecs(0xc042038460, 0xc0420ea5d0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:113 +0x18b
github.com/getgauge/gauge/api/lang.getDiagnostics(0x8, 0x9f2b50, 0xc95728)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:73 +0x8d
github.com/getgauge/gauge/api/lang.publishDiagnostics(0xc46300, 0xc04200e410, 0xc44580, 0xc042284f60)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:52 +0xa6
created by github.com/getgauge/gauge/api/lang.documentChange
	src/github.com/getgauge/gauge/api/lang/server.go:255 +0x256
[Info  - 6:00:43 PM] Connection to server got closed. Server will restart.
[Error - 6:00:44 PM] Request textDocument/codeLens failed.
  Message: failed to parse specification c:\work\testFolder\jstest\basic1\specs\example.spec
  Code: 0 
[Error - 6:00:46 PM] Request textDocument/codeLens failed.
  Message: failed to parse specification c:\work\testFolder\jstest\basic1\specs\example.spec
  Code: 0 
```

**Steps to replicate**
* Yet to find steps to consistently replicate it.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-12
Commit Hash: 8166611

Plugins
-------
csharp (0.10.2.nightly-2018-01-18)
dotnet (0.0.1.nightly-2018-02-12)
html-report (4.0.3.nightly-2017-12-08)
java (0.6.7.nightly-2018-01-22)
js (2.1.1.nightly-2018-02-08)
python (0.2.4.nightly-2018-02-11)
ruby (0.4.3.nightly-2018-02-07)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
