### ISSUE TITLE
Editing specification results in Index out of range exception

### ISSUE THREAD

**Issue by imonthercks** [getgauge/gauge-vscode#158]
**Expected Behavior**
Should be able to work seamlessly

**Actual Behavior** 
![image](https://user-images.githubusercontent.com/1477296/36815106-4ed3c0b8-1c9f-11e8-910f-60fe7168294a.png)
```
goroutine 35 [running]:
github.com/getgauge/gauge/api/lang.(*files).line(0xc710a0, 0xc0421d82d0, 0x44, 0x18, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/file.go:49 +0xf3
github.com/getgauge/gauge/api/lang.getLine(0xc0421d82d0, 0x44, 0x18, 0x8ebfa0, 0xc0421d6d60)
	src/github.com/getgauge/gauge/api/lang/file.go:80 +0x52
github.com/getgauge/gauge/api/lang.completion(0xc042380370, 0x17, 0x9d527f, 0x17, 0x1)
	src/github.com/getgauge/gauge/api/lang/completion.go:57 +0xe0
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0xc8e898, 0xc3f2c0, 0xc04203e460, 0xc3d540, 0xc04221bec0, 0xc042380370, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:138 +0xf58
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0xc8e898, 0xc3f2c0, 0xc04203e460, 0xc04221bec0, 0xc042380370, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:109 +0x6d
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0xc3f2c0, 0xc04203e460, 0xc04221bec0, 0xc042380370, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:101 +0x59
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc0421854f0, 0xc3f2c0, 0xc04203e460, 0xc04221bec0, 0xc042380370)
	src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x76
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	src/github.com/getgauge/gauge/api/lang/server.go:105 +0x72
[Info  - 3:38:34 PM] Connection to server got closed. Server will restart.
[Error - 3:38:34 PM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\cj.BRANDON\.vscode\extensions\getgauge.gauge-0.0.4\node_modules\vscode-jsonrpc\lib\events.js:135:36)
panic: runtime error: index out of range
```

**Steps to replicate**
This occurs directly after attempting to add a new step to a spec file (as soon as asterisk is typed).  We saw this same issue with both csharp and dotnet runners. 

**Version**
VSCode Version on Windows 10
![image](https://user-images.githubusercontent.com/1477296/36815305-ee3c9242-1c9f-11e8-9eef-23bdc93d69d8.png)

```
PS C:\svn\NAPA-PreOpAssessment\tests\gauge> gauge version
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
csharp (0.10.1)
dotnet (0.0.1.nightly-2018-02-23)
html-report (4.0.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by nehashri** [comment]
@imonthercks Thanks for reporting this issue. 
We are currently working on fixing the bugs with Gauge LSP server. We will be releasing the stable version of VSCode soon. The currently supported languages for VSCode is only Javascript. However, such issues shall be addressed with the new release. 
Full support for csharp and dotnet in VSCode will be added later.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
