### ISSUE TITLE
User should be able to debug

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#207]
**Actual behavior**
Getting the following error while debugging a specification
```
Debugger listening on ws://127.0.0.1:63567/f601ab59-dc41-4cf8-b710-4f81c862aa1c
For help see https://nodejs.org/en/docs/inspector
  Error Message: Error: connect ECONNREFUSED 127.0.0.1:4444
  Stacktrace: 
  Error: connect ECONNREFUSED 127.0.0.1:4444
      at new RuntimeError (node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
      at Request._callback (node_modules\webdriverio\build\lib\utils\RequestHandler.js:330:43)
      at self.callback (node_modules\request\request.js:186:22)
      at Request.emit (events.js:159:13)
      at Request.onRequestError (node_modules\request\request.js:878:8)
      at ClientRequest.emit (events.js:164:20)
      at Socket.socketErrorListener (_http_client.js:389:9)
      at Socket.emit (events.js:159:13)
      at emitErrorNT (internal/streams/destroy.js:64:8)
```
**Steps to replicate**
* Create a `gauge init js_webdriver`
* Open the project in VSCode
* Put breakpoints in steps 
```
step("Go to Gauge homepage at <query>", async function (query) {
  await client.url(query);
});

step("Go to Get Started page", async function () {
  await client.click("a.btn-primary");
});
```
* Run the specs in debug spec mode
> Observe the above error

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-14
Commit Hash: 0ac4700

Plugins
-------
js (2.2.0.nightly-2018-03-19)
```

**Comment by sguptatw** [comment]
Working as expected
