### ISSUE TITLE
Navigate to file with test failures from the console output

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#23]
**Proposed behavior**
When a scenario fails, after a run inside VS Code. 
The user can click on failure stack trace to navigate to the file and line of failure.

**Acceptance criteria**
- [ ] If the failure message is
```
 ## IDE Plugins
        
        Failed Step: Display the IDE plugins
        Specification: specs/example.spec:37
        Error Message: AssertionError: false == true
        Stacktrace: 
        AssertionError: false == true
            at step (tests/step_implementation.js:67:12)
            at process._tickCallback (internal/process/next_tick.js:109:7)
```
`specs/example.spec:37` and `tests/step_implementation.js:67:12` must be links that navigate to the line that cause the test failure.

**Comment by zabil** [comment]
Refer https://github.com/Microsoft/vscode/issues/586#issuecomment-248184108

**Comment by sriv** [comment]
I guess <kbd>CTRL</kbd>+`Click` on windows works only on absolute path of the files. 

If gauge is changed to yield something like this:

```
Running tool: gauge run c:\Temp\baz\specs\example.spec:14 --simple-console --hide-suggestion
# Specification Heading
  ## Vowel counts in single word
        
        Failed Step: The word "gauge" has "3" vowels.
        Specification: c:\Temp\baz\specs\example.spec:19
        Error Message: AssertionError [ERR_ASSERTION]: '3' == 4
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: '3' == 4
            at Object.<anonymous> (tests\step_implementation.js:24:10)
            at Test.runFn (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\test.js:51:23)
            at Test.run (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\test.js:83:11)
            at Object.executeStep [as step] (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\executor.js:46:42)
            at MessageProcessor.executeStep (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\message-processor.js:31:26)
            at MessageProcessor.getResponseFor (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\message-processor.js:171:40)
            at ExecutionConnection.<anonymous> (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\gauge.js:23:17)
            at emitOne (events.js:115:13)
            at ExecutionConnection.emit (events.js:210:7)
            at Socket.messageHandler (C:\Users\steam\AppData\Roaming\gauge\plugins\js\2.0.2\src\connection.js:17:10)

generating spec c:\Temp\baz\specs\example.spec
Successfully generated html-report to => c:\Temp\baz\reports\html-report\index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

```

Then the file navigation from the failure output works (including line numbers).

https://github.com/Microsoft/vscode/issues/586#issuecomment-248184108 is not very clean, and I don't think the complexity justifies such a change (unless we build our own gauge's specific output).

**Comment by zabil** [comment]
Yes changing the output is fine.
Does it go the line number of failure?

**Comment by sguptatw** [comment]
In the js file, it is going to the next line after the failure

**Comment by sriv** [comment]
gauge-vscode has no control on the line no printed on the console, it merely navigates to the location printed.

this should be an error in gauge-js, I suppose.
