### ISSUE TITLE
Activating extension `getgauge.gauge` failed

### ISSUE THREAD

**Issue by jagretz** [getgauge/gauge-vscode#383]
I am not entirely sure if this is an issue with the extension or VS Code, or perhaps when installing/running behind a corporate firewall but I am having trouble running the extension.

Everything in VSCode looks swell and i don't have any notifications. I simply can't use the extension features other than "Gauge: Create a new Gauge Project" and "Report an issue".

I have tried reinstalling the plugin, restarting vscode, manually downloading and installing the extension (not from marketplace), restarting windows 😅 

**Deets:**
- Win x64 10.0.1.17763
- vscode version 1.35.1
- node v10.15.3
- npm 6.4.1
- gauge vscode extension v0.0.10

Additionally, I am using (windows version of) nvm, and I will also note that I do not have gauge installed globally. It is only installed local to my project dir.

Running `gauge -v` produces the following information:

```bash
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
```

```js
workbench.main.js:3187 Activating extension 'getgauge.gauge' failed: Unexpected end of JSON input.
_logMessageInConsole @ workbench.main.js:3187
```
```js
workbench.main.js:238 [Extension Host] Activating extension `getgauge.gauge` failed:  Unexpected end of JSON input
t.log @ workbench.main.js:238
```
```js
workbench.main.js:238 [Extension Host] Here is the error stack:  SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Function.instance (C:\Users\gretzj\.vscode\extensions\getgauge.gauge-0.0.10\out\extension.js:1:13405)
	at C:\Users\gretzj\.vscode\extensions\getgauge.gauge-0.0.10\out\extension.js:1:8593
	at Generator.next (<anonymous>)
	at module.exports.n (C:\Users\gretzj\.vscode\extensions\getgauge.gauge-0.0.10\out\extension.js:1:8359)
	at new Promise (<anonymous>)
	at module.exports.n (C:\Users\gretzj\.vscode\extensions\getgauge.gauge-0.0.10\out\extension.js:1:8136)
	at module.exports.t.activate (C:\Users\gretzj\.vscode\extensions\getgauge.gauge-0.0.10\out\extension.js:1:8548)
	at Function._callActivateOptional (c:\Users\gretzj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:936)
	at Function._callActivate (c:\Users\gretzj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:625)
	at define._doActivateExtension.Promise.all.then.e (c:\Users\gretzj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:737:635)
```

**Comment by nehashri** [comment]
@jagretz Are you seeing this error with the sample project created?

**Comment by jagretz** [comment]
@nehashri I ran through the initial (documented) install steps for Taiko and Gauge which included some samples.

**Comment by nehashri** [comment]
@jagretz Can you please let me know the node version you are using. Also, please run `gauge -v` and paste its contents here.

**Comment by jagretz** [comment]
I have updated the original post with the relevant information -- I should have provided that first, along with my OS version. Sorry about that.

**Comment by BugDiver** [comment]
>  I do not have gauge installed globally.

@jagretz The plugin currently does not work with a local installation of the gauge. It needs `gauge` to be installed globally( or available in PATH). Or else it shows an error pop up saying `Gauge executable not found! Click here for install instructions.`.

Seems like you have installed an instance of gauge globally or the local path of the gauge is available to PATH.

Can you please verify this?

**Comment by jagretz** [comment]
Thanks for the reply @BugDiver 
I only have a local instance of Gauge installed and it is not available on my PATH. That must be the problem, thanks for the input!

**Comment by NivedhaSenthil** [comment]
@jagretz can you please confirm if it works after installing gauge globally ?

**Comment by Apoorva-GA** [comment]
@jagretz Feel free to reopen the issue if you are still facing the problem
