### ISSUE TITLE
Cannot submit issue

### ISSUE THREAD

**Issue by jberumen3** [getgauge/gauge-vscode#685]
### Describe the bug
When I am implementing a new step in my Spec, it gives me a light bulb asking to help generate a step:
![image](https://user-images.githubusercontent.com/52225468/123908151-e0024b80-d92b-11eb-8feb-18ca465940ab.png)

Then, I click on create a new file
![image](https://user-images.githubusercontent.com/52225468/123908205-f1e3ee80-d92b-11eb-8934-7eb513c95ce5.png)

After clicking on new file, there is an error message: 
![image](https://user-images.githubusercontent.com/52225468/123908270-0b853600-d92c-11eb-9f8d-0724c4a97a58.png)

Only options seems to work is add to existing `StepImplementation.ts` file but only that one works, the clipboard doesn't work either. 

One thing I am trying out is specifying a nested directory in the `ts.properties` file. 

### What command(s) did you run when you found the bug?
None. In VSCode.

### Output, stack trace or logs related to the bug
Error message:
```
Unable to generate implementation. Error: error while connecting to runner : rpc error: code = Internal desc = Cannot read property 'end' of null
TypeError: Cannot read property 'end' of null
    at StubImplementationCodeProcessor.diffForImplementationInExistingClass (c:\Users\Gilfoyle\Repos\Extension\node_modules\gauge-ts\dist\processors\StubImplementationCodeProcessor.js:41:69)
    at StubImplementationCodeProcessor.process (c:\Users\Gilfoyle\Repos\Extension\node_modules\gauge-ts\dist\processors\StubImplementationCodeProcessor.js:23:33)
    at RunnerServiceImpl.implementStub (c:\Users\Gilfoyle\Repos\Extension\node_modules\gauge-ts\dist\RunnerServiceImpl.js:193:73)
    at handleUnary (c:\Users\Gilfoyle\Repos\Extension\node_modules\@grpc\grpc-js\src\server.ts:667:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Versions
"gauge-ts": "^0.1.0",

#### Gauge (Output of `gauge -v`)
```
Gauge version: 1.2.1
Commit Hash: fa7918b

Plugins
-------
html-report (4.0.12)
screenshot (0.0.1)
ts (0.1.0)
```
#### Node.js/Java/Python/.Net/Ruby version
Node.Js v14.17.1

#### Operating System information
Windows 10 

#### IDE information
VSCode

**Comment by sriv** [comment]
This might have something to do with gauge-ts. Please, can you report this issue at https://github.com/BugDiver/gauge-ts
