### ISSUE TITLE
The error path is getting concatenated with relative path twice

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#79]
**Expected behavior**
The error path in the stacktrace should be correct

**Actual behavior**
The error path is getting concatenated with relative path twice

**Steps to replicate**
* Project - [WrongPathInJS.zip](https://github.com/getgauge-contrib/gauge-js/files/1557923/WrongPathInJS.zip)
* npm install
* Run spec `concept diagnostics.spec`
> Observe the error stack having multiple relative paths
```
TypeError: vscodeUri.file is not a function
            at Object.getFullPath (...\getgauge\gauge-lsp-tests\...\getgauge\gauge-lsp-tests\tests\util\fileExtension.js:8:22)
            at Object.startGaugeDaemon (...\getgauge\gauge-lsp-tests\tests\lsp\daemon.js:14:30)
            at Object.<anonymous> (tests\gaugeDaemon.js:4:18)
```

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

**Comment by sguptatw** [comment]
This issue was moved to getgauge-contrib/gauge-js#88
