### ISSUE TITLE
The error path in the stack trace is incomplete

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#80]
**Expected behavior**
The error path in the stack trace should be complete

**Actual behavior**
The error path is incomplete

**Steps to replicate**
* Run project [errors_with_incomplete_Path.zip](https://github.com/getgauge/gauge-vscode/files/1566895/errors_with_incomplete_Path.zip)
> Observe the path in the error
```
AssertionError [ERR_ASSERTION]: 0 not equal to 1
            at verifyAutocompleteResponse (tests\codecomplete.js:59:12)
            at Object.<anonymous> (tests\codecomplete.js:29:5)
```
**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

**Comment by sguptatw** [comment]
This issue was moved to getgauge-contrib/gauge-js#87
